<script setup lang="ts">
import * as echarts from "echarts";
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from "vue";

const views = [["market", "Market"], ["silver", "Silver"], ["gold", "Gold"], ["f10", "F10"], ["industry", "Industry"], ["runs", "Runs"], ["partitions", "Partitions"], ["quarantine", "Quarantine"], ["package", "Package"], ["storage", "Storage"], ["quality", "Quality"], ["freshness", "Freshness"]] as const;
const view = ref("market"); const query = ref(""); const rows = ref<Record<string, unknown>[]>([]); const total = ref(0); const loading = ref(false); const error = ref(""); const chartElement = ref<HTMLElement>(); let chart: echarts.ECharts | undefined;
const columns = computed(() => Object.keys(rows.value[0] || {}).slice(0, 8));
async function load() { loading.value = true; error.value = ""; try { const params = new URLSearchParams({ page_size: "500", q: query.value.trim() }); const response = await fetch(`/api/data/${encodeURIComponent(view.value)}?${params}`); if (!response.ok) throw new Error("数据浏览器加载失败"); const data = await response.json() as { items: Record<string, unknown>[]; total: number }; rows.value = data.items; total.value = data.total; await nextTick(); renderChart(); } catch (reason) { error.value = reason instanceof Error ? reason.message : "数据浏览器加载失败"; rows.value = []; total.value = 0; } finally { loading.value = false; } }
function renderChart() { if (!chartElement.value) return; chart ??= echarts.init(chartElement.value); const labels = rows.value.slice(0, 20).map((row, index) => String(row.partition_id || row.provider || row.chain || row.instrumentKey || row.area || index + 1)); const values = rows.value.slice(0, 20).map((row) => Number(row.row_count || row.rows || row.bytes || row.issue_count || row.value || 1)); chart.setOption({ backgroundColor: "transparent", grid: { top: 22, left: 55, right: 16, bottom: 58 }, xAxis: { type: "category", data: labels, axisLabel: { color: "#91a0b7", rotate: 28 } }, yAxis: { type: "value", axisLabel: { color: "#91a0b7" }, splitLine: { lineStyle: { color: "#26334c" } } }, series: [{ type: "bar", data: values, itemStyle: { color: "#4f8cff" } }] }); }
watch(view, () => void load()); onMounted(() => { void load(); window.addEventListener("resize", renderChart); }); onBeforeUnmount(() => { window.removeEventListener("resize", renderChart); chart?.dispose(); });
</script>

<template><section><h1 class="page-title">数据</h1><p class="page-note">Grafana 风格本地只读监查；服务端仅提供受控视图、筛选、排序与最多 500 行预览，不暴露任意 SQL。</p><el-alert v-if="error" :title="error" type="warning" :closable="false" class="page-alert" /><section class="panel data-controls"><el-select v-model="view"><el-option v-for="[key,label] in views" :key="key" :label="label" :value="key" /></el-select><el-input v-model="query" placeholder="服务端筛选" clearable @keyup.enter="load" /><el-button type="primary" :loading="loading" @click="load">查询</el-button><span class="muted">{{ total }} 条，预览最多 500 条</span></section><section class="panel"><div ref="chartElement" class="data-chart" /></section><section class="panel"><el-table :data="rows" v-loading="loading" max-height="520"><el-table-column v-for="column in columns" :key="column" :prop="column" :label="column" min-width="150" show-overflow-tooltip /></el-table></section></section></template>
