<script setup lang="ts">
import { onMounted, ref } from "vue";
import { formatCategory, formatOperation, formatStatus, formatTime } from "../domain/api";
interface EventRow { timestamp: string; category: string; status?: string; operation?: string; detail?: string }
const category = ref(""); const rows = ref<EventRow[]>([]); const total = ref(0); const loading = ref(false);
async function load() { loading.value = true; try { const params = new URLSearchParams({ page_size: "500" }); if (category.value) params.set("category", category.value); const response = await fetch(`/api/logs?${params}`); if (!response.ok) throw new Error(); const data = await response.json() as { items: EventRow[]; total: number }; rows.value = data.items; total.value = data.total; } finally { loading.value = false; } }
onMounted(() => void load());
</script>
<template><section><h1 class="page-title">日志</h1><p class="page-note">本机 `logs/events-YYYY-MM-DD.jsonl` 的追加式事件记录；用于审计任务操作、数据源、行情、F10、研报、产业链、Android、数据质量与异常，不替代业务数据。</p><section class="panel data-controls"><el-select v-model="category" clearable placeholder="全部类别"><el-option v-for="item in ['Operation','Market','F10','Report','Industry','Android','Provider','Quality']" :key="item" :label="formatCategory(item)" :value="item" /></el-select><el-button type="primary" :loading="loading" @click="load">筛选</el-button><span class="muted">{{ total }} 条，最多预览 500 条</span></section><section class="panel"><el-table :data="rows" v-loading="loading" max-height="600"><el-table-column label="时间" min-width="190"><template #default="scope">{{ formatTime(scope.row.timestamp) }}</template></el-table-column><el-table-column label="类别" width="150"><template #default="scope">{{ formatCategory(scope.row.category) }}</template></el-table-column><el-table-column label="操作" min-width="160"><template #default="scope">{{ formatOperation(scope.row.operation) }}</template></el-table-column><el-table-column label="状态" width="150"><template #default="scope">{{ formatStatus(scope.row.status) }}</template></el-table-column><el-table-column prop="detail" label="详情" min-width="260" show-overflow-tooltip /></el-table></section></section></template>
